#!/bin/bash

# lets get this machine updated
sudo apt update
sudo apt upgrade -y

# All this just for eza?
sudo apt install -y gpg
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza

# Configure zsh
cp -f .zshrc ~/.zshrc
cp -f .p10k.zsh ~/.p10k.zsh

# Get theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k



#Install fzf for that sweet ctrl+r
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all --no-update-rc

# install z as cd alternative
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

# keep this handy to keep bundles thin
npm i -g npm-why

# I hate to do this everytime
git config --global --add --bool push.autoSetupRemote true

# workspace config :)
mkdir -p /workspaces/vofficeGmbh
cp working.code-workspace /workspaces/vofficeGmbh
